import { Router } from 'express';
import authRoutes from './auth.js';
import userRoutes from './users.js';
import activityRoutes from './activities.js';
import notificationRoutes from './notifications.js';
import clubRoutes from './clubs.js';
import challengeRoutes from './challenges.js';
import routeRoutes from './routes.js';
import rankingRoutes from './rankings.js';
import xpRoutes from './xp.js';
import achievementRoutes from './achievements.js';
import metricsRoutes from './metrics.js';
import aiCoachRoutes from './ai-coach.js';
import trainingPlanRoutes from './training-plans.js';
import trainingWizardRoutes from './training-wizard.js';
import heatmapRoutes from './heatmaps.js';
import integrationRoutes from './integrations.js';
import importRoutes from './imports.js';
import webhookRoutes from './webhooks.js';
import adminRoutes from './admin.js';
import moderationRoutes from './moderation.js';
// import subscriptionRoutes from './subscriptions.js';
// import billingRoutes from './billing.js';
// import referralRoutes from './referrals.js';
// import couponRoutes from './coupons.js';
// import sponsorRoutes from './sponsors.js';
import segmentRoutes from './segments.js';
import eventRoutes from './events.js';
import chatRoutes from './chats.js';
import shareRoutes from './share.js';
import badgeRoutes from './badges.js';
import discoverRoutes from './discover.js';
import recommendationRoutes from './recommendations.js';
import racePredictionRoutes from './race-predictions.js';
import publicApiRoutes from './public-api.js';
import marketplaceRoutes from './marketplace.js';
import translationRoutes from './translations.js';
import analyticsRoutes from './analytics.js';

const router = Router();

router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/activities', activityRoutes);
router.use('/notifications', notificationRoutes);
router.use('/clubs', clubRoutes);
router.use('/challenges', challengeRoutes);
router.use('/routes', routeRoutes);
router.use('/rankings', rankingRoutes);
router.use('/xp', xpRoutes);
router.use('/achievements', achievementRoutes);
router.use('/metrics', metricsRoutes);
router.use('/ai', aiCoachRoutes);
router.use('/training-plans', trainingPlanRoutes);
router.use('/training-wizard', trainingWizardRoutes);
router.use('/heatmaps', heatmapRoutes);
router.use('/integrations', integrationRoutes);
router.use('/imports', importRoutes);
router.use('/webhooks', webhookRoutes);
router.use('/admin', adminRoutes);
router.use('/moderation', moderationRoutes);
// router.use('/subscriptions', subscriptionRoutes);
// router.use('/billing', billingRoutes);
// router.use('/referrals', referralRoutes);
// router.use('/coupons', couponRoutes);
// router.use('/sponsors', sponsorRoutes);
router.use('/segments', segmentRoutes);
router.use('/events', eventRoutes);
router.use('/chats', chatRoutes);
router.use('/share', shareRoutes);
router.use('/badges', badgeRoutes);
router.use('/discover', discoverRoutes);
router.use('/recommendations', recommendationRoutes);
router.use('/race-predictions', racePredictionRoutes);
router.use('/public-api', publicApiRoutes);
router.use('/marketplace', marketplaceRoutes);
router.use('/translations', translationRoutes);
router.use('/analytics', analyticsRoutes);

export default router;
